# Generated by Django 2.1 on 2018-08-07 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('party_symbol', models.EmailField(max_length=254)),
                ('flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('public_key', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidates', models.ManyToManyField(blank=True, related_name='Elections', to='api.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Candidate')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=20)),
                ('unique_code', models.TextField(max_length=20)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Voter'),
        ),
        migrations.AddField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='Elections', to='api.Voter'),
        ),
    ]
