# Generated by Django 2.1 on 2018-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party_symbol',
            field=models.TextField(max_length=100),
        ),
    ]
