# Generated by Django 2.1 on 2018-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180807_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='unique_code',
            field=models.CharField(max_length=20),
        ),
    ]
