# Generated by Django 2.1 on 2018-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180809_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party_symbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='election',
            name='public_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='election',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
