# Generated by Django 2.1 on 2018-08-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180809_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
